### ISSUE TITLE
Implement a tie strategy for bundle? 

### ISSUE THREAD

**Issue by benjamin-asdf** [gigasquid/vsa-clj#3]
Currently the bundle / clip implementation leaves the zeros, if there is a tie in bundle. 

Afaik there are multiple candidates to resolve ties and which one has 
some pros and cons  I'm not sure about.

**Comment by gigasquid** [comment]
Hi @benjamin-asdf !

The are quite a few implementations of VSA that handle these:
With Kanerva's BSC implementation, you can add a random vector while summing to break ties. In other implementations like Plate's real value HRR, zero is a perfectly valid value and no one cares - it will happen infrequently enough.

I've gone with the Gayler MAP system, that initializes the vectors at -1 and 1, but after that clips the magnitudes and ignores ties in summation - you still could inject a low magnitude noise vector if you want. I found it unneeded for what I was doing, but it might be useful in your case.

**Comment by benjamin-asdf** [comment]
Yea it's true, usually doesn't matter :D   

For future travelers, they might be interested in https://link.springer.com/article/10.1007/s10462-021-10110-3
